### PR TITLE
Implement a more efficient vertical grid generation

### PR DESCRIPTION
**Pull request by Simon-Lopez**
The new method is more efficient (around 15 times faster) and spares
a if switch (isOnYAxis test).
The old implementation has been left.

### CODE REVIEW

**Comment by twinkelmann** [comment]
[BUG: Topographic surface takes faults color](https://trello.com/c/TXKxNYDn/1488-bug-topographic-surface-takes-faults-color)

**Comment by twinkelmann** [comment]
To determine what this change was and if we need to merge it.

**Comment by Simon-Lopez** [comment]
> To determine what this change was and if we need to merge it.

Oops it's a bit old. From what I read of my own comment, it is supposed to speed up computation.
Yet as I do not have a testing environment for geocruncher I could not really test if it did not break something...

**Comment by twinkelmann** [comment]
Okay, once I cleaned everything else, I'll try it. The profiling will make it easy to assess the performance improvement :+1:

**Comment by Simon-Lopez** [comment]
It will only concern meshes with fractures… and it’s 15x speed-up only for the function (so it depends how much it represent in the total process)

De : Tim Winkelmann ***@***.***>
Envoyé : vendredi 29 septembre 2023 13:35
À : ISSKA/geocruncher ***@***.***>
Cc : Lopez Simon ***@***.***>; Author ***@***.***>
Objet : Re: [ISSKA/geocruncher] Implement a more efficient vertical grid generation (PR #63)


Okay, once I cleaned everything else, I'll try it. The profiling will make it easy to assess the performance improvement 👍

**Pull request merged**
