### PR TITLE
Fix intersections on CS broken when x1=x2

### PR DESCRIPTION
**Pull request by simhayoz**
see: https://trello.com/c/ECET7hkX/1170-intersections-on-cs-broken-when-x1x2

### CODE REVIEW

**Comment by simhayoz** [comment]
> LGTM, it may be a good idea to add a test to the test_geocruncher.py

I agree, but seeing the current tests, we will have to do a full test suite and it is not an easy task knowing that it comes from an external library. I will ask @ArnauldMalard, if it is worth spending some times or if manual testing is enough for this kind script

**Comment by cintoros** [comment]
> I agree, but seeing the current tests, we will have to do a full test suite and it is not an easy task knowing that it comes from an external library. I will ask @ArnauldMalard, if it is worth spending some times or if manual testing is enough for this kind script

If we have to do a full test suite it is probably not worth it for such a small codebase. I have just seen that we already had some tests.

**Comment by simhayoz** [comment]
> If we have to do a full test suite it is probably not worth it for such a small codebase. I have just seen that we already had some tests.

After discussion with @ArnauldMalard:
I will make some tests for the slice and we will have to just keep in mind that the current tests are clearly not enough and that we could try to add some every time we make some change on this code.

**Comment by simhayoz** [comment]
I don't use it and just forgot to remove it, it is done now

**Pull request merged**
